services:
  letters-to-steve:
    image: ghcr.io/jackharrhy/letters-to-steve
    build: .
    ports:
      - "127.0.0.1:4321:4321"

  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - ./data/libsql:/var/lib/sqld
